**PERSIAPAN DATASET**

dataset yang digunakan : https://www.kaggle.com/datasets/himelsarder/retail-product-dataset-with-missing-values

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
import pandas as pd

dataset = '/content/drive/MyDrive/Colab Notebooks/synthetic_dataset.csv'
data = pd.read_csv(dataset)
data

     Category   Price    Rating         Stock  Discount
0         NaN  5548.0  1.870322           NaN       0.0
1         NaN  3045.0  4.757798           NaN      38.0
2         NaN  4004.0       NaN      In Stock       0.0
3         NaN  4808.0  1.492085           NaN      33.0
4         NaN  1817.0       NaN  Out of Stock      23.0
...       ...     ...       ...           ...       ...
4357      NaN  4436.0  4.728335           NaN      49.0
4358        B  6236.0       NaN  Out of Stock       4.0
4359      NaN  3283.0       NaN  Out of Stock       9.0
4360        D  2999.0  4.425995           NaN      40.0
4361      NaN     NaN  2.184471           NaN       0.0

[4362 rows x 5 columns]

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   object
 1   Price     4362 non-null   float64
 2   Rating    4362 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  3970 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

**IDENTIFIKASI MISSING VALUE**

In [45]:
# mendefinsiikan format missing value
missing_value=["N.A", "na", "n.a.", "n/a", "-"," "]

# menmabhkan parameter na_values untuk memformat missing_value
data = pd.read_csv(dataset, na_values=missing_value)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   object
 1   Price     4188 non-null   float64
 2   Rating    2312 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  3970 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

**MEMERIKSA MISSING VALUE DATAFRAME**

In [46]:
# memeriksa missing value kseseluruhan
data.isna().values.any()

# memeriksa missing values setiap kolom
data.isna().any()

Category    True
Price       True
Rating      True
Stock       True
Discount    True
dtype: bool

**MENGHITUNG JUMLAH MISSING VALUE**

In [47]:
# memeriksa missing value tiap kolom
data.isna().sum()

Category    2748
Price        174
Rating      2050
Stock       1352
Discount     392
dtype: int64

**MENGHAPUS BARIS YANG MENGANDUNG MISSING VALUE**

In [48]:
# menghapus baris yang mengandung missing value pada kolom Stock
data.dropna(subset=["Stock"], axis=0, inplace=True)

# mereset index karena ada data terhapus
data.reset_index(drop=True, inplace=True)

data

     Category   Price    Rating         Stock  Discount
0         NaN  4004.0       NaN      In Stock       0.0
1         NaN  1817.0       NaN  Out of Stock      23.0
2           C   667.0  3.668341      In Stock      41.0
3           A  7125.0  4.983998  Out of Stock       7.0
4           A  2777.0  2.678384      In Stock       6.0
...       ...     ...       ...           ...       ...
3005      NaN  1556.0  1.433035      In Stock       NaN
3006      NaN     NaN       NaN      In Stock      46.0
3007      NaN     NaN       NaN  Out of Stock      21.0
3008        B  6236.0       NaN  Out of Stock       4.0
3009      NaN  3283.0       NaN  Out of Stock       9.0

[3010 rows x 5 columns]

**MENGISI MISSING VALUE DENGAN NILAI TERTENTU**

In [49]:
# mengisi missing value pada kolom Category dengan Other
data["Category"].fillna("Other", inplace=True)

#mengisi missing value pada kolom discount dengan 0
data["Discount"].fillna(0,inplace=True)
data

/tmp/ipython-input-2010648168.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Category"].fillna("Other", inplace=True)
/tmp/ipython-input-2010648168.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Discount"].fillna(0,inplace=True)

     Category   Price    Rating         Stock  Discount
0       Other  4004.0       NaN      In Stock       0.0
1       Other  1817.0       NaN  Out of Stock      23.0
2           C   667.0  3.668341      In Stock      41.0
3           A  7125.0  4.983998  Out of Stock       7.0
4           A  2777.0  2.678384      In Stock       6.0
...       ...     ...       ...           ...       ...
3005    Other  1556.0  1.433035      In Stock       0.0
3006    Other     NaN       NaN      In Stock      46.0
3007    Other     NaN       NaN  Out of Stock      21.0
3008        B  6236.0       NaN  Out of Stock       4.0
3009    Other  3283.0       NaN  Out of Stock       9.0

[3010 rows x 5 columns]

**MENGISI MISSING VALUE DENGAN MEAN/MEDIAN**

In [50]:
# mengisi missing value pada kolom Price dengan mean
data["Price"].fillna(data["Price"].mean(), inplace=True)

# mengisi missing value pada kolom Rating dengan median
data["Rating"].fillna(data["Rating"].median(), inplace=True)

data

/tmp/ipython-input-1309114371.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Price"].fillna(data["Price"].mean(), inplace=True)
/tmp/ipython-input-1309114371.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Rating"].fillna(data["Rating"].median(), inplace=True)

     Category        Price    Rating         Stock  Discount
0       Other  4004.000000  3.081697      In Stock       0.0
1       Other  1817.000000  3.081697  Out of Stock      23.0
2           C   667.000000  3.668341      In Stock      41.0
3           A  7125.000000  4.983998  Out of Stock       7.0
4           A  2777.000000  2.678384      In Stock       6.0
...       ...          ...       ...           ...       ...
3005    Other  1556.000000  1.433035      In Stock       0.0
3006    Other  5024.705208  3.081697      In Stock      46.0
3007    Other  5024.705208  3.081697  Out of Stock      21.0
3008        B  6236.000000  3.081697  Out of Stock       4.0
3009    Other  3283.000000  3.081697  Out of Stock       9.0

[3010 rows x 5 columns]

In [51]:
data.isna().sum()

Category    0
Price       0
Rating      0
Stock       0
Discount    0
dtype: int64

**MEMERIKSA DUPLIKAT DATA**

dataset yang digunakan adalah dataset ILPD (Indian Liver Patient Dataset)
https://www.kaggle.com/datasets/jeevannagaraj/indian-liver-patient-dataset

In [54]:
import pandas as pd

# menambahkan header
column_name=["Age","Gender","Total Bilirubin", "Direct Bilirubin", "Alkaline Phosphotase", "SGPT","SGOT","Total Protein", "Albumin", "Albumin and Globulin Ratio", "Class"]
dataset1 = '/content/drive/MyDrive/Colab Notebooks/Indian-Liver-Patient-Dataset-(ILPD).csv'
data1= pd.read_csv(dataset1, names=column_name)
data1

,Age,Gender,Total Bilirubin,Direct Bilirubin,Alkaline Phosphotase,SGPT,SGOT,Total Protein,Albumin,Albumin and Globulin Ratio,Class
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60,Male,0.5,0.1,500,20,34,5.9,1.6,0.37,2
579,40,Male,0.6,0.1,98,35,31,6.0,3.2,1.10,1
580,52,Male,0.8,0.2,245,48,49,6.4,3.2,1.00,1
581,31,Male,1.3,0.5,184,29,32,6.8,3.4,1.00,1
582,38,Male,1.0,0.3,216,21,24,7.3,4.4,1.50,2

In [55]:
# memeriksa duplikat dataframe
data1.duplicated().values.any()

np.True_

true menandakan bahwa ada data duplikat.

In [56]:
# memeriksa duplikat per baris
data1.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
578    False
579    False
580    False
581    False
582    False
Length: 583, dtype: bool

In [57]:
# menampilkan semua baris data yang sama
data1[data1.duplicated(keep=False)]

,Age,Gender,Total Bilirubin,Direct Bilirubin,Alkaline Phosphotase,SGPT,SGOT,Total Protein,Albumin,Albumin and Globulin Ratio,Class
18,40,Female,0.9,0.3,293,232,245,6.8,3.1,0.80,1
19,40,Female,0.9,0.3,293,232,245,6.8,3.1,0.80,1
25,34,Male,4.1,2.0,289,875,731,5.0,2.7,1.10,1
26,34,Male,4.1,2.0,289,875,731,5.0,2.7,1.10,1
33,38,Female,2.6,1.2,410,59,57,5.6,3.0,0.80,2
34,38,Female,2.6,1.2,410,59,57,5.6,3.0,0.80,2
54,42,Male,8.9,4.5,272,31,61,5.8,2.0,0.50,1
55,42,Male,8.9,4.5,272,31,61,5.8,2.0,0.50,1
61,58,Male,1.0,0.5,158,37,43,7.2,3.6,1.00,1
62,58,Male,1.0,0.5,158,37,43,7.2,3.6,1.00,1
105,36,Male,5.3,2.3,145,32,92,5.1,2.6,1.00,2
106,36,Male,5.3,2.3,145,32,92,5.1,2.6,1.00,2
107,36,Male,0.8,0.2,158,29,39,6.0,2.2,0.50,2
108,36,Male,0.8,0.2,158,29,39,6.0,2.2,0.50,2
137,18,Male,0.8,0.2,282,72,140,5.5,2.5,0.80,1
138,18,Male,0.8,0.2,282,72,140,5.5,2.5,0.80,1
142,30,Male,1.6,0.4,332,84,139,5.6,2.7,0.90,1
143,30,Male,1.6,0.4,332,84,139,5.6,2.7,0.90,1
157,72,Male,0.7,0.1,196,20,35,5.8,2.0,0.50,1
158,72,Male,0.7,0.1,196,20,35,5.8,2.0,0.50,1
163,39,Male,1.9,0.9,180,42,62,7.4,4.3,1.38,1
164,39,Male,1.9,0.9,180,42,62,7.4,4.3,1.38,1
173,31,Male,0.6,0.1,175,48,34,6.0,3.7,1.60,1
174,31,Male,0.6,0.1,175,48,34,6.0,3.7,1.60,1
200,49,Male,0.6,0.1,218,50,53,5.0,2.4,0.90,1
201,49,Male,0.6,0.1,218,50,53,5.0,2.4,0.90,1

In [58]:
# menampilkan data pertama yang duplikat
data1[data1.duplicated(keep="first")]

,Age,Gender,Total Bilirubin,Direct Bilirubin,Alkaline Phosphotase,SGPT,SGOT,Total Protein,Albumin,Albumin and Globulin Ratio,Class
19,40,Female,0.9,0.3,293,232,245,6.8,3.1,0.80,1
26,34,Male,4.1,2.0,289,875,731,5.0,2.7,1.10,1
34,38,Female,2.6,1.2,410,59,57,5.6,3.0,0.80,2
55,42,Male,8.9,4.5,272,31,61,5.8,2.0,0.50,1
62,58,Male,1.0,0.5,158,37,43,7.2,3.6,1.00,1
106,36,Male,5.3,2.3,145,32,92,5.1,2.6,1.00,2
108,36,Male,0.8,0.2,158,29,39,6.0,2.2,0.50,2
138,18,Male,0.8,0.2,282,72,140,5.5,2.5,0.80,1
143,30,Male,1.6,0.4,332,84,139,5.6,2.7,0.90,1
158,72,Male,0.7,0.1,196,20,35,5.8,2.0,0.50,1
164,39,Male,1.9,0.9,180,42,62,7.4,4.3,1.38,1
174,31,Male,0.6,0.1,175,48,34,6.0,3.7,1.60,1
201,49,Male,0.6,0.1,218,50,53,5.0,2.4,0.90,1

In [59]:
# menampikan data kedua duplikat
data1[data1.duplicated(keep="last")]

,Age,Gender,Total Bilirubin,Direct Bilirubin,Alkaline Phosphotase,SGPT,SGOT,Total Protein,Albumin,Albumin and Globulin Ratio,Class
18,40,Female,0.9,0.3,293,232,245,6.8,3.1,0.80,1
25,34,Male,4.1,2.0,289,875,731,5.0,2.7,1.10,1
33,38,Female,2.6,1.2,410,59,57,5.6,3.0,0.80,2
54,42,Male,8.9,4.5,272,31,61,5.8,2.0,0.50,1
61,58,Male,1.0,0.5,158,37,43,7.2,3.6,1.00,1
105,36,Male,5.3,2.3,145,32,92,5.1,2.6,1.00,2
107,36,Male,0.8,0.2,158,29,39,6.0,2.2,0.50,2
137,18,Male,0.8,0.2,282,72,140,5.5,2.5,0.80,1
142,30,Male,1.6,0.4,332,84,139,5.6,2.7,0.90,1
157,72,Male,0.7,0.1,196,20,35,5.8,2.0,0.50,1
163,39,Male,1.9,0.9,180,42,62,7.4,4.3,1.38,1
173,31,Male,0.6,0.1,175,48,34,6.0,3.7,1.60,1
200,49,Male,0.6,0.1,218,50,53,5.0,2.4,0.90,1

**MENGHAPUS DUPLIKAT DATA**

In [31]:
data1.drop_duplicates(keep="first", inplace=True)
data1

,Age,Gender,Total Bilirubin,Direct Bilirubin,Alkaline Phosphotase,SGPT,SGOT,Total Protein,Albumin,Albumin and Globulin Ratio,Class
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
565,60,Male,0.5,0.1,500,20,34,5.9,1.6,0.37,2
566,40,Male,0.6,0.1,98,35,31,6.0,3.2,1.10,1
567,52,Male,0.8,0.2,245,48,49,6.4,3.2,1.00,1
568,31,Male,1.3,0.5,184,29,32,6.8,3.4,1.00,1
569,38,Male,1.0,0.3,216,21,24,7.3,4.4,1.50,2

In [60]:
# mereset index
data1.reset_index(drop=True, inplace=True)
data1

,Age,Gender,Total Bilirubin,Direct Bilirubin,Alkaline Phosphotase,SGPT,SGOT,Total Protein,Albumin,Albumin and Globulin Ratio,Class
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60,Male,0.5,0.1,500,20,34,5.9,1.6,0.37,2
579,40,Male,0.6,0.1,98,35,31,6.0,3.2,1.10,1
580,52,Male,0.8,0.2,245,48,49,6.4,3.2,1.00,1
581,31,Male,1.3,0.5,184,29,32,6.8,3.4,1.00,1
582,38,Male,1.0,0.3,216,21,24,7.3,4.4,1.50,2

**DATA FORMATTING**

mengubah format data menjadi bentuk lain yang lebih sesuai. Menggunakan dataset pertama synthetic_dataset.csv

In [41]:
# memeriksa tipe data
data.dtypes

Category     object
Price       float64
Rating      float64
Stock        object
Discount    float64
dtype: object

In [52]:
# mengubah tipe data kolom "Diskon" menjadi integer
data["Discount"]=data["Discount"].astype("int64")
data

     Category        Price    Rating         Stock  Discount
0       Other  4004.000000  3.081697      In Stock         0
1       Other  1817.000000  3.081697  Out of Stock        23
2           C   667.000000  3.668341      In Stock        41
3           A  7125.000000  4.983998  Out of Stock         7
4           A  2777.000000  2.678384      In Stock         6
...       ...          ...       ...           ...       ...
3005    Other  1556.000000  1.433035      In Stock         0
3006    Other  5024.705208  3.081697      In Stock        46
3007    Other  5024.705208  3.081697  Out of Stock        21
3008        B  6236.000000  3.081697  Out of Stock         4
3009    Other  3283.000000  3.081697  Out of Stock         9

[3010 rows x 5 columns]

In [53]:
# mengecek tipe data "Discount" kembali
data.dtypes

Category     object
Price       float64
Rating      float64
Stock        object
Discount      int64
dtype: object